Require datepick

# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 46
Set Width 1200
Set Height 500
Set LineHeight 1.8

# Type a command in the terminal.
Type "datepick"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 1s

Set TypingSpeed 0.2

Up
Up

Sleep 0.5s

Right

Sleep 0.5s

Down
Down

Sleep 0.5s

Right

Sleep 0.5s

Up

Sleep 1s

Enter

Sleep 5s
